[package]
name = "manga-theka"
version = "0.1.0"
authors = ["Vladislav Gardner <vladislavgardner@proton.me>"]
edition = "2024"
description = "API backend for Manga Theka"
documentation = "TODO"
readme = "README.md"
homepage = "TODO"
repository = "https://github.com/v1adhope/manga-theka"
license-file = "LICENSE"

[lib]
path = "src/lib.rs"

[[bin]]
name = "manga-theka"
path = "src/main.rs"

[[test]]
name = "api"
path = "tests/api/mod.rs"

[dependencies]
axum = { version = "0.8", features = ["multipart"] }
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
  "net",
  "signal",
  "sync",
  "time",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "fmt",
  "json",
  "time",
] }
tracing-log = "0.2"
uuid = { version = "1", features = ["v7", "serde"] }
time = { version = "0.3", features = ["serde", "serde-human-readable"] }
sqlx = { version = "0.9", features = [
  "runtime-tokio",
  "postgres",
  "macros",
  "migrate",
  "uuid",
  "time",
] }
thiserror = "2"
url = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
secrecy = { version = "0.10", features = ["serde"] }
envious = "0.3"
aws-sdk-s3 = { version = "1", default-features = false, features = [
  "rt-tokio",
  "behavior-version-latest",
  "default-https-client",
] }
bytes = "1"
aws-config = { version = "1", default-features = false, features = [
  "rt-tokio",
  "default-https-client",
  "behavior-version-latest",
] }
anyhow = "1"
regex = "1"
sanitize-filename = "0.6"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
fake = "5"
axum-test = "21"
