services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${APP_DATABASE__PASSWORD}
      POSTGRES_USER: ${APP_DATABASE__USERNAME}
      POSTGRES_DB: ${APP_DATABASE__DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${APP_DATABASE__USERNAME} -d $${APP_DATABASE__DATABASE_NAME}",
        ]
      interval: 1s
      timeout: 5s
      retries: 10

  rustfs:
    image: rustfs/rustfs:latest
    restart: always
    ports:
      - "9000:9000"
    environment:
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_VOLUMES: /data/rustfs0
      RUSTFS_ACCESS_KEY: ${APP_OBJECT_STORAGE__ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${APP_OBJECT_STORAGE__SECRET_KEY}
      RUSTFS_CONSOLE_ENABLE: "false"
    volumes:
      - rustfsdata:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:9000/health"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  rustfsdata:
