services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${APP_DATABASE__PASSWORD}
      POSTGRES_USER: ${APP_DATABASE__USERNAME}
      POSTGRES_DB: ${APP_DATABASE__DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${APP_DATABASE__USERNAME} -d $${APP_DATABASE__DATABASE_NAME}",
        ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
